name: Build Lyra

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Install Dependencies
        run: go get .
        
      - name: Build Lyra
        run: ./build.sh

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
  	    with:
          name: lyra
    	    path: bin/
